//
//  TestStyleKit.swift
//  Cacao
//
//  Created by Alsey Coleman Miller on 5/12/16.
//  Copyright (c) 2016 PureSwift. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

import Silica
import Cacao
import SwiftCoreGraphics
import SwiftUIKit

public final class TestStyleKit {

    //// Drawing Methods

    public class func drawCanvas1(frame: Rect = Rect(x: 0, y: 0, width: 240, height: 120)) {
        //// Color Declarations
        let color2 = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 1.000)
        let color3 = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: Rect(x: frame.minX + floor(frame.width * 0.00000 + 0.5), y: frame.minY + floor(frame.height * 0.00000 + 0.5), width: floor(frame.width * 1.00000 + 0.5) - floor(frame.width * 0.00000 + 0.5), height: floor(frame.height * 1.00000 + 0.5) - floor(frame.height * 0.00000 + 0.5)))
        color3.setFill()
        rectanglePath.fill()


        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: Rect(x: frame.minX + floor(frame.width * 0.33333 + 0.5), y: frame.minY + floor(frame.height * 0.16667 + 0.5), width: floor(frame.width * 0.66667 + 0.5) - floor(frame.width * 0.33333 + 0.5), height: floor(frame.height * 0.83333 + 0.5) - floor(frame.height * 0.16667 + 0.5)))
        color2.setFill()
        ovalPath.fill()
    }

    public class func drawCanvas2(frame: Rect = Rect(x: 0, y: 0, width: 240, height: 120)) {
        //// Color Declarations
        let color3 = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let color4 = UIColor(red: 0.151, green: 0.277, blue: 0.801, alpha: 1.000)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: Rect(x: frame.minX + floor(frame.width * 0.00000 + 0.5), y: frame.minY + floor(frame.height * 0.00000 + 0.5), width: floor(frame.width * 1.00000 + 0.5) - floor(frame.width * 0.00000 + 0.5), height: floor(frame.height * 1.00000 + 0.5) - floor(frame.height * 0.00000 + 0.5)))
        color3.setFill()
        rectanglePath.fill()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: Rect(x: frame.minX + 95, y: frame.minY + 35, width: 50, height: 50))
        color4.setFill()
        rectangle2Path.fill()
    }

}
